<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1, **Align Shapes From the Right**: When comparing two arrays for compatibility to do some opration, align their shapes from the right (i.e., compare starting from the last axis)

2, **Two Dimensions are Compatible If *they are equal* or one of them is 1**

In [3]:
#  Scalar and 1D array at this point  the scalar shap append by one two match to the larger shape and become (1, ) and the given other
#  array let say A = (n, )  B = ()-> (1, ) then do  the opration

A = np.array([1, 2, 4, 5,6])
B = 5
print(A + B)
#  Behind the scene B = [5] and then this one element expand again to become same with the larger size and become B = [5, 5,5, 5,5]
#  then the above opt become opration on the   A = [1, 2, 4, 5, 6] and B = [5, 5, 5, 5, 5] and do the opration

[ 6  7  9 10 11]




- 1D and 1D(array) with the same shape



In [4]:
# If the shape of the arrays is same we can do the opration with out any modification
A = np.array([1, 2, 4, 5])
B = np.array([10, 20, 30, 40])
print(A + B)

[11 22 34 45]


- 1D and 2D

In [5]:
A = np.array([1, 2, 4])
B = np.array([[4], [5], [6]])
A + B

# Behind the scene due to broad cast the two array become
#  A = [[1, 2, 4]] first after this point it also append this value again and  again to use for all value in the secon
#  A  = [[1, 2, 4], [1, 2, 4], [1, 2, 4]]
#  A  = [[4, 4, 4], [5, 5, 5], [6, 6, 6]]
#  R = [[5, 6, 8], [6, 7, 9], [7, 8, 10]]


array([[ 5,  6,  8],
       [ 6,  7,  9],
       [ 7,  8, 10]])

In [6]:
#  shap of A =  (1, 3)
A = np.array([[1, 2, 3]])
#  shape of B = (2, 1)
B = np.array([[4], [5]])
#  Bxehind The scene due to the broadcast the above opt is possible
#  A = [[1, 2, 3], [1, 2, 3]]
#  B = [[4, 4, 4], [5, 5, 5]]
#  R = [[5, 6, 7], [6, 7, 8]]
A + B

array([[5, 6, 7],
       [6, 7, 8]])

In [8]:
A = 10                      # Shape: ()
B = np.array([[[1, 2, 3]]]) # Shape: (1, 1, 3)
#  When we compare the shape start from the make the scala to (1, ) means = A = [10]
#  then compare the shap start from the left (1, ) and (1, 1, 3) --> it have the ast most one is one and due to the broadcast the shap of A become
#  (1, 1, 1) == [[[1]]] and add the same value untill we get the sme shape A = [[[10, 10, 10]]]
#  Behind the scene the array movment
#  A = [[[10, 10, 10]]]
#  B = [[[1, 2, 3]]]
#  R = [[[11, 12, 13]]]
result = A +  B
print(result)

[[[11 12 13]]]


In [9]:
A = np.array([1, 2, 3])          # Shape: (3,)
B = np.array([[[4]], [[5]]])     # Shape: (2, 1, 1)

#  behind the scene A shape appended by 1 until it have same shape with other A shape become = (1, 1, 3)
#  comapare (1, 1, 3) and (2, 1, 1) when we compare the dim from the last one is 1 then we can do the opt using boadcating
#  A = [[[1, 2, 3]], [[1, 2, 3]]]
#  B = [[[4, 4, 4]], [[5, 5, 5]]]

result = A + B
print(result)

[[[5 6 7]]

 [[6 7 8]]]
