<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/practice_problems/empty_full_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# How to create an empty and a full NumPy array?

In [26]:
#  The aboove problem asked about how can we create empty and full Numpy array
#  the structure of the the empty method is np.empty(shape, data_type)
#  It contain garbage value

# empty_arr = np.empty((3))
# empty_arr = np.empty((3, 3))
empty_arr = np.empty((3, 3, 1))


empty_arr

array([[[95427113564561],
        [             0],
        [             0]],

       [[             0],
        [             0],
        [             0]],

       [[             0],
        [             0],
        [             0]]])

In [29]:
#  We can add data type
# empty_arr = np.empty((3, 4), dtype=bool)
empty_arr = np.empty((3, 4), dtype=int)
empty_arr

array([[95427111963714,              0,              0,              0],
       [             0,              0,              0,              0],
       [             0,              0,              0,              0]])

In [38]:
#  we can use full method of numpy to create arr with value of fill_value

full_arr = np.full(shape = (3, 3), fill_value=20)
full_true = np.full(shape=(4, 4), fill_value=True)
full_true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])