<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [14]:
data = np.arange(1, 36)
new_data = data.reshape((5, -1))
mean = np.arange(7, 14)
std_div = np.arange(14, 21)
new_data


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [16]:
mean

array([ 7,  8,  9, 10, 11, 12, 13])

In [18]:
#  Normalize the data first subtract the mean from all element and devide all element using the std_div


#  first calculate the diff = data - mean
#  to do that we have to conver the mean to 1 x 3 shape
normal = (new_data - mean[np.newaxis, :])/mean[np.newaxis, :]
normal

array([[-0.85714286, -0.75      , -0.66666667, -0.6       , -0.54545455,
        -0.5       , -0.46153846],
       [ 0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909,
         0.08333333,  0.07692308],
       [ 1.14285714,  1.        ,  0.88888889,  0.8       ,  0.72727273,
         0.66666667,  0.61538462],
       [ 2.14285714,  1.875     ,  1.66666667,  1.5       ,  1.36363636,
         1.25      ,  1.15384615],
       [ 3.14285714,  2.75      ,  2.44444444,  2.2       ,  2.        ,
         1.83333333,  1.69230769]])

In [21]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
bias = np.array([1, 2, 3])
result = matrix + bias
result

array([[11, 22, 33],
       [41, 52, 63]])