<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Using Normal Python List To Least All Prices of The Year In Seconds Interal and
It Take About **7.852016448974609** seconds

In [ ]:
import time

start_time = time.time()

prices = []

N = 60 * 60 * 24*365

print(N)

for second in range(N):
  prices.append(100 + second/ 100)

print(prices[:10])

end_time = time.time()

print("Time Taken : ", end_time - start_time)


31536000
[100.0, 100.01, 100.02, 100.03, 100.04, 100.05, 100.06, 100.07, 100.08, 100.09]
Time Taken :  7.796318769454956


- Calculate The Avarage Price of The Year Using Normal List Take More Than 4 secons

In [ ]:
avarage = 0
start_time = time.time()



for price in prices:
  avarage += price / N

end_time = time.time()



print("Avarage Price Of The Year Become : ", avarage)
print("Avarage Price Of The Year Take : ", end_time-start_time)


Avarage Price Of The Year Become :  157779.995
Avarage Price Of The Year Take :  4.684968709945679


In [ ]:
import numpy as np

- Doing The List Of Prices For The Year Is Realy Fast In Numpy

In [ ]:
start_time = time.time()
prices = 100 + np.arange(N) / 100
print(prices[:10])
end_time = time.time()
print("Time Taken By Numpy To List All Prices : ", end_time - start_time)

[100.   100.01 100.02 100.03 100.04 100.05 100.06 100.07 100.08 100.09]
Time Taken By Numpy To List All Prices :  0.2569618225097656


In [ ]:
start_time = time.time()
avarage = prices.mean()
print("Avarage Of 1 Year Prices : ", avarage)
end_time = time.time()
print("Time Taken : ", end_time - start_time)

Avarage Of 1 Year Prices :  157779.995
Time Taken :  0.026510953903198242


- We can Create Numpy Array From Every List Of Object in python set, tuple and list

In [ ]:
py_list = [1, 2, 3, 4, 5]

py_set = set(py_list)

py_tuple = (1, 2, 3, 4,5)

arr = np.array(py_set)
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
arr = np.array([
    [2, 1, 3, 4],
    [2, 3, 4, 5],
    [2, 3, 10, 5],

])

length = len(arr)
print("Length : ", length)
element_count = np.size(arr)
print("Total Element Count : ", element_count)
arr_shape = np.shape(arr)

print("Arr Shape : ", arr_shape)






Length :  3
Total Element Count :  12
Arr Shape :  (3, 4)


In [ ]:

arr = np.array([1, 2, 3, 4, 5])
length = len(arr)
print("Length : ", length)
element_count = np.size(arr)
print("Total Element Count : ", element_count)
arr_shape = np.shape(arr)

print("Arr Shape : ", arr_shape)

arr = np.array([1])
print(arr)


Length :  5
Total Element Count :  5
Arr Shape :  (5,)
[1]


In [ ]:
orginal_arr = np.array([1, 2, 3, 4, 5])

np_arr = np.array(orginal_arr, copy=False )
np_arr [-1] = 100

print(np_arr)
print(orginal_arr)


[  1   2   3   4 100]
[  1   2   3   4 100]


- Diffenet Dimension Array In Numpy

In [ ]:
# 0D
zero_dim = np.array(1)
print("Size : ", np.size(zero_dim))
print("Shape : ", np.shape(zero_dim))
print("Dimensions : ", zero_dim.ndim)
# 1D
one_dim = np.array([1, 2, 3, 4, 5])
print("Size : ", np.size(one_dim))
print("Shape : ", np.shape(one_dim))
print("Dimensions : ", one_dim.ndim)


#  2D
two_dim = np.array([
    [1, 2, 3, 4, 5],
    [10, 4, 3, 4, 5],
    [17, 2, 39, 42, 5]
])
print("Size : ", np.size(two_dim))
print("Shape : ", np.shape(two_dim))
print("Dimensions : ", two_dim.ndim)

#  3D
three_dim = np.array([
    [
    [1, 2, 3, 4, 5],
    [10, 4, 3, 4, 5],
    [17, 2, 39, 42, 5]
], [
    [10, 20, 30, 40, 5],
    [10, 4, 23, 24, 5],
    [17, 2, 39, 42, 5]
]
])
print("Size : ", np.size(three_dim))
print("Shape : ", np.shape(three_dim))
print("Dimensions : ", three_dim.ndim)



Size :  1
Shape :  ()
Dimensions :  0
Size :  5
Shape :  (5,)
Dimensions :  1
Size :  15
Shape :  (3, 5)
Dimensions :  2
Size :  30
Shape :  (2, 3, 5)
Dimensions :  3


- Fill Same Values With Numpy Functions

In [ ]:
#  Fill All Value with zeros with give shape
#  Example Of 1D fill with string, number and float , boolean
ages = np.full(fill_value=20, shape=3)
print(ages)
names = np.full(fill_value="Monkey D Luffy", shape=3)
names
print(names)
registrations_fags = np.full(fill_value=True, shape=3)
print(registrations_fags)


ages = np.full(fill_value=20, shape=(3, 2,3))
print(ages)
names = np.full(fill_value="Monkey D Luffy", shape=(3, 2,3))
names
print(names)
registrations_fags = np.full(fill_value=True, shape=(3, 2,3))
print(registrations_fags)




[20 20 20]
['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']
[ True  True  True]
[[[20 20 20]
  [20 20 20]]

 [[20 20 20]
  [20 20 20]]

 [[20 20 20]
  [20 20 20]]]
[[['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']
  ['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']]

 [['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']
  ['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']]

 [['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']
  ['Monkey D Luffy' 'Monkey D Luffy' 'Monkey D Luffy']]]
[[[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


- Create Series of Values and Random Value


1.   numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None): create List of Number with in the given range which  either infered from the default  or created maualy
2.   random.randint(low, high=None, size=None, dtype=int) : used to create radome integer between low and high with **replacment**



In [ ]:
one_dim_series = np.arange(18)
print("Generated Array : ", one_dim_series)

evens = np.arange(0, 18, 2)
print("evens : ", evens)


#  radome values


radoms_1d = np.random.randint(0, 5, size = 5)
print("Random Values : ", radoms_1d)


radoms_2d = np.random.randint(0, 5, size = (3, 6))
print("Random Values : ", radoms_2d)


radoms_3d = np.random.randint(0, 5, size = (2, 3, 3))
print("Random Values : ", radoms_3d)

Generated Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
evens :  [ 0  2  4  6  8 10 12 14 16]
Random Values :  [2 4 4 3 1]
Random Values :  [[0 2 0 1 2 1]
 [4 2 2 1 4 1]
 [4 2 3 0 1 1]]
Random Values :  [[[3 2 3]
  [2 1 4]
  [0 0 3]]

 [[0 3 1]
  [0 1 0]
  [4 1 0]]]
