<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/numpy_multi_dim_array_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [44]:
#  Create 3 x 3 array or mat
arr = np.random.randint(20,54, size = (3,3))

#  accessing Single element
print("Element At SomeSpesfic Row And Col :" ,arr[1][2])



[[27 35 31]
 [25 37 37]
 [20 46 38]]


37

In [48]:
#  Accessing All Element In Given Row

print("All Elemet In Some Given Row :",arr[1])

#  Accessing MultipleRow UsingSlicing On Row
print("All Elemet In Multiple Rows :", arr[:2])

All Elemet In Some Given Row : [25 37 37]
All Elemet In Multiple Rows : [[27 35 31]
 [25 37 37]]


In [54]:
# AccessAllElement In some Column
print("All Element In Somespec Col : ",arr[:,1])

#  Accessing MultipleColumns
print("All Element In Multiple Columns : ",arr[:,[0,2]])

All Element In Somespec Col :  [35 37 46]
All Element In Multiple Columns :  [[27 31]
 [25 37]
 [20 38]]
