<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/opration_on_the_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

- We Can Add To array asif they are scalar if they have same shape and let say we have n X m matrix named as A and B

*   if the shape is same we can add them as scalars i.e   R = A + B
*   if the shape is same we can sub  them as scalar i.e   R = A - B
*   if the shape is same we can multiply them as scalar i.e R = A * B
*   if the shape is same we can divide them as scalar i.e R = A/ b





In [55]:
#  Example using  For 1D
prices1 = np.array([10, 20, 30, 40, 50])

prices2 = np.array([100, 200, 300, 400, 500])


In [59]:
#  Add Two Same Shapped Array
total_prices = prices1 + prices2
print(total_prices)
#  subtract

final_prices = prices2 - prices1
print(final_prices)
#  Multiply Two Values
new_prices = prices1 * prices2
print(new_prices)
last_prices = prices2 / prices1
print(last_prices)


[110 220 330 440 550]
[ 90 180 270 360 450]
[ 1000  4000  9000 16000 25000]
[10. 10. 10. 10. 10.]


In [60]:
prices1 = np.array([[
    [10, 20, 30, 40, 50],
    [101, 200, 303, 40, 50]
], [
    [10, 20, 30, 40, 50],
    [101, 200, 303, 40, 50]
]])

prices2 = np.array([[
    [10, 20, 30, 40, 50],
    [101, 20, 303, 40, 50]
], [
    [10, 200, 300, 400, 50],
    [101, 200, 303, 40, 50]
]])

In [62]:
#  Shape of the above two arrays are the same which is 2x2x5 and we can do add, sub , div, mul as if they are scalar
add_r = prices1 + prices2

print("Added : ", add_r)

sub_r = prices2 - prices1

print("Sub : ", sub_r)

mul_r = prices1 * prices2
print("Mul : ", mul_r)
div_r = prices2/ prices1
print("Div : ", div_r)

Added :  [[[ 20  40  60  80 100]
  [202 220 606  80 100]]

 [[ 20 220 330 440 100]
  [202 400 606  80 100]]]
Sub :  [[[   0    0    0    0    0]
  [   0 -180    0    0    0]]

 [[   0  180  270  360    0]
  [   0    0    0    0    0]]]
Mul :  [[[  100   400   900  1600  2500]
  [10201  4000 91809  1600  2500]]

 [[  100  4000  9000 16000  2500]
  [10201 40000 91809  1600  2500]]]
Div :  [[[ 1.   1.   1.   1.   1. ]
  [ 1.   0.1  1.   1.   1. ]]

 [[ 1.  10.  10.  10.   1. ]
  [ 1.   1.   1.   1.   1. ]]]


In [64]:
#  Multipley With Scalar

prices3 = np.array([[
    [10, 20, 30, 40, 50],
    [101, 200, 303, 40, 50]
], [
    [10, 20, 30, 40, 50],
    [101, 200, 303, 40, 50]
]])

prices4 = np.array([100, 200, 300, 400, 500])



In [66]:
#  add scalar to all element value with k

prices4_new = prices4 + 100
# prices4_new = prices4 * 100 multipley all element by 100
# prices4_new = prices4 / 100 divide all element by 100
# prices4_new = prices4 - 100 subtract 100 from all element




print(prices4_new)

[200 300 400 500 600]


In [67]:
prices3_new = prices3 + 1000
print(prices3_new)
# prices3_new = prices3 * 1000 multipley all element by 1000
# prices3_new = prices3 / 1000 divide all element by 1000
# prices3_new = prices3 - 1000 subtract 1000 from all element


[[[1010 1020 1030 1040 1050]
  [1101 1200 1303 1040 1050]]

 [[1010 1020 1030 1040 1050]
  [1101 1200 1303 1040 1050]]]
