<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/problems_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
#  Generate Integer Between low and high(exclusive) by default it generate single number but we can give the shape correctly

np.random.randint(1, 101, size=(3, 4))

array([[64, 23, 15, 22],
       [90, 16, 23, 32],
       [ 6, 73, 44, 21]])

In [11]:
#  Generate Floating Number generate between the range with  0 - 1 and we ca pass the shape as parameter
np.random.rand(2, 3, 2)

array([[[0.2732837 , 0.51536529],
        [0.27791105, 0.82530109],
        [0.12870131, 0.96374401]],

       [[0.03816658, 0.99335976],
        [0.12441806, 0.54036972],
        [0.27231433, 0.9520467 ]]])

In [16]:
# random.choice used to select element from the arrayb we passed as an argument and it must one deminsional


arr =  np.random.randint(10, 200, 20)
np.random.choice(arr)

25

In [22]:
#  Shuffle shuff;e the values in places and o return value
arr = [1, 2, 3, 4, 5]
arr_new = np.random.permutation(arr)
np.random.shuffle(arr)
print(arr_new)
print(arr)
#  if just one integer for permutation it generate permutation array of length 0 - n-1 or length of n
permutation_arr = np.random.permutation(8)
permutation_arr


[1 2 4 5 3]
[2, 1, 5, 3, 4]


array([3, 1, 4, 2, 5, 7, 0, 6])

In [28]:
#  Generate random number from uniformly distribute distribution

arr = np.random.normal(loc=0, scale= 2, size = 9)
print(arr)

[ 0.83706876  2.62674918  3.11295687 -4.05860144  0.6226431   1.68387508
  2.7177928  -1.34782867 -1.16427265]


In [30]:
x = np.random.uniform(low=0, high=10, size=5)  # 5 samples from a uniform distribution
print(x)

[1.16147642 3.89834916 2.6234408  9.45437497 1.81571153]


In [36]:
np.random.seed(11)
np.random.randint(1, 20)

17

In [37]:
from os import replace
arr  = np.array(["We", "can", "Use", "Random", "On", "String", "As Well"])
np.random.choice(
    arr,
    size=(2, 2),
    replace=True,

)

array([['Random', 'can'],
       ['String', 'On']], dtype='<U7')

In [51]:
arr = np.arange(1, 7)
#  p is used to define the probablity of the number in the list
np.random.choice(arr, size=3, p=[0, 0, 0, 0.1, 0.2, 0.7], replace=True)


array([6, 4, 6])

In [52]:
#  np.random.bet is used ti generte random number from beta dist
np.random.seed(42)  # For reproducibility
a, b = 2, 5
sample = np.random.beta(a, b, size=1)
print("Random Beta sample:", sample)

Random Beta sample: [0.35367666]


In [66]:
#  permutation used to permuttion np.array or generate array depend on the first parmmeter
#  permutation(x)
#  if x is integer it act like np.arange(x) --> generate permuation of x
#  if x is 1d array it create the permutation of the array and retured the permuated array
#  if the array is multidimentional it return the array with permutated one axis

arr = np.arange(1, 10)
print(arr)
# for passing normmal integer
print(np.random.permutation(10))
#  For One Demension Array
per_arr = np.random.permutation(arr)

print(per_arr)

#  When we pass multi demensional array
m_arr = np.reshape(arr, newshape=(3, 3))
#  orginal array
print(m_arr)
# the permutated array it permutate according to the first dim that mean permute the rows
print(np.random.permutation(m_arr))

[1 2 3 4 5 6 7 8 9]
[9 5 8 6 7 3 1 2 0 4]
[3 7 8 5 4 2 9 6 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [69]:
# np.random.rand is ussed to generate random number between 0 and 1 which is uniform
#  it accept shape as parameter and if we dont pass any it return single floating number

print(np.random.rand(3, 4))
print(np.random.rand())

[[0.18651851 0.04077514 0.59089294 0.67756436]
 [0.01658783 0.51209306 0.22649578 0.64517279]
 [0.17436643 0.69093774 0.38673535 0.93672999]]
0.13752094414599325


In [84]:
#  random.randint(low, high=None, size=None, dtype=int)
#   low is integer or array of integer(what does it mean when we pass the start as array whih aact as multiple start)  ad act like the high when there isno other parameter
#  high is interger or rray with same reason and it is exclusive
#  size = it is either interger or tuple pf value if we dont give the value it use the length as the dim
#  we can also pass the data type

# example 1 with only low it give single random value between 0 - low -1
print(" Example 1 : ", np.random.randint(10))
#  passing low and high which give single element selected from low - high - 1
print("Example 2 : ", np.random.randint(20, 31))
#  passing low , high and the size of random numbe generated size dim
print("Example 3", np.random.randint(32, 40, size=(3, )))
#  we can pass pass list of low amd high value
print("Example 4 : ", np.random.randint([43, 54, 88], [50, 70, 90], size=(3, 3)))
#  we can also pass the data type
print("Example 5 : ", np.random.randint(10, 20, dtype=np.int64))

 Example 1 :  0
Example 2 :  23
Example 3 [38 36 36]
Example 4 :  [[49 54 89]
 [45 69 89]
 [43 63 88]]
Example 5 :  15


In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#  accessing single element

# print(arr_2d[2, 1])

#  accesssing multiple element using tuple idex
# print(arr_2d[[1], [1, 2]])
#  slicing
print(arr_2d[0:, 1:])



[[2 3]
 [5 6]
 [8 9]]


In [15]:
#  boolean indexing
even_arr_bool =arr_2d % 2 == 0
print(arr_2d[even_arr_bool])

[2 4 6 8]


In [34]:
arr1 = np.arange(1, 25)
arr1.shape=(2, 3, 4)
print(arr1)
arr1[:, 1:2, 2:]


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


array([[[ 7,  8]],

       [[19, 20]]])

In [39]:
arr2 = np.random.randint(2, 101, size = (3, 4))
print(arr2)
np.where(arr2 % 2 == 0)

[[80 79 20 73]
 [ 9 55  3 67]
 [25  8 94 60]]


(array([0, 0, 2, 2, 2]), array([0, 2, 1, 2, 3]))