<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/problems_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1, How to Remove rows in Numpy array that contains non-numeric values?
   Answer
   - First use isnan to check the element is nan or number.if it is nan it return true else false and finally return boolean array of the same size
   - and find row with any(at leats one nan) value is true and create boolean value for all row
   - after that we remove row that is have any true after isnan is excute and return boolarray
   - numpy use the boolean indexing to give us the remaining value
  NB : we can manage the axis using the axis option of the any which help us to determine the axis we remove
-

In [50]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [23.45, 50, 78.7],
                  [41, np.nan, np.nan]])

#  apply the isnan and it return boolean array with same shap
nan_places = np.isnan(n_arr)
#  we find any row or col (as our requirment) with at least one true(nan value)
rows_value = nan_places.any(axis=1)
#  toggle the value of the above array which tell us row with nan value false this help us to us the
#  array as boolan indexing
~rows_value
#  then use the boolean array as index and it return row with no nan value
n_arr[~rows_value]



array([[10.5 , 22.5 ,  3.8 ],
       [23.45, 50.  , 78.7 ]])

In [51]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [23.45, 50, 78.7],
                  [41, np.nan, np.nan]])
#  we can do the above shortly using below
n_arr[~np.isnan(n_arr).any(axis=1)]

array([[10.5 , 22.5 ,  3.8 ],
       [23.45, 50.  , 78.7 ]])

# 2, Remove single-dimensional entries from the shape of an array ?
Answer
- using squeeze method of np and pass axis along with it which help us to remove all unnessary 1 demintion
 case_one = if we dont pass axis this remove all 1 deminsion
 case_two  =  if we pass axis remove that axis if it is equal to one otherwise it give typeError

In [59]:
arr = np.arange(12)
arr.shape = (1, 1, 2, 2, 3)
arr.squeeze(axis=(0,1))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# 3 Find the number of occurrences of a sequence in a NumPy array ?
Answer
1, use np.lib.stride_tricks.sliding_window_view(arr, len(sequence))

In [69]:


arr = np.array([1, 2, 3, 1, 2, 3, 4, 1, 2, 3])


sequence = np.array([1, 2, 3])


#  create which consit of the length of len(squence) X len(arr) - len(sequnce) + 1 maatric

window_arr = np.lib.stride_tricks.sliding_window_view(arr, len(sequence))
window_bool = window_arr==sequence
#  then count all row(axis=1) with all true
same_window = np.all(window_bool, axis=1)
np.sum(same_window)





3

In [81]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9], [10, 20, 30]])

sequence = np.array([4, 5, 6])

# Sliding window view:
windows = np.lib.stride_tricks.sliding_window_view(arr1, len(sequence), axis=1) == sequence
np.sum(np.all(windows, axis=1))


3