<a href="https://colab.research.google.com/github/nuredinbedruyimer/machine_learning/blob/main/where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
#  Where is Used to filter some data and appley some change based on that
#  for example we need to replace the negative price with avarage of the positive sales
sales_data = np.array([
    [100, -5, 200],
    [150, -20, 300]
])

#  step one create boolean index to filter all positive sales
positive_sales_bool_index = sales_data > 0
#  then filtwr the data based on the above boolean index and filter the data
positive_sales = sales_data[positive_sales_bool_index]
#  the find the mean
avarage_sale = np.mean(positive_sales)
#  then filter all negative sales and replace with the avarage
cleaned_data = np.where(sales_data < 0, avarage_sale, sales_data)
cleaned_data



array([[100. , 187.5, 200. ],
       [150. , 187.5, 300. ]])

In [13]:
#  let us see broadcasting as an example
row_array, col_array = np.ogrid[:3, :4]
#  the actual shape of the above is looks like below
# row_array = [[0],
#              [1],
#              [2]]
# col_array = [[0, 1, 2, 3]]

#  case-1 : calculating the condtion from two broadcasting array and then used tht as condtion

# row_array  = [[0, 0, 0, 0],
#              [1, 1, 1, 1],
#              [2, 2, 2, 2]]
# col_array = [[0, 1, 2, 3],
#              [0, 1, 2, 3],
#              [0, 1, 2, 3]]

# then compare the value element wise

np.where(row_array == col_array, row_array, 100 + col_array)

#  the result will be below
# [[0, 1, 2, 3],
#  [0, 1, 2, 3],
#  [0, 1, 2, 3]]




array([[  0, 101, 102, 103],
       [100,   1, 102, 103],
       [100, 101,   2, 103]])

array([30. , 13. , 32.5])

In [36]:
arr = np.random.randint(0, 2, size=(4, 4))

arr
#  np.array(array, axis = None, out=None, keeepdims = False)

#  1 just pass array which leads to finding just one element that make the condtion true if it get return single value true other wise False
np.any(arr)
#  2, pass the axis number it condense the array along that axis let exampe say we use axis= 0 it condense along the column it return 1 X columns_number

np.any(arr, axis=0)
#  3, passing the keepdim which keep the dimention
np.any(arr, keepdims=True)
np.any(arr, axis=1, keepdims=True)




array([[ True],
       [False],
       [ True],
       [ True]])